### ISSUE TITLE
Jotkut HTML-kommenttien linkit vanhentuneet repositorion uudelleennimeämisen takia

### ISSUE THREAD

**Issue by bluelhf** [digitoimistodude/dude-2020#5]
Sivun lähdekoodia tutkiville tarkoitetut HTML-kommentit osoittavat vielä `digitoimistodude/dude`-repositorioon, joka ei ole saatavilla (ainakaan julkisesti).

Linkit löytyvät mm. [GitHub:in hausta](https://github.com/digitoimistodude/dude-2020/search?q=github.com/digitoimistodude/dude).

Korjaaminen tapahtuisi yksinkertaisesti vaihtamalla kaikki `github.com/digitoimistodude/dude`-linkit `github.com/digitoimistodude/dude-2020`-linkeiksi.

**Comment by ronilaukkarinen** [comment]
Moi! Hyvä huomio, mutta tällä ei ole oikeastaan merkitystä, koska tämä repo jää arkistoon uuden tieltä. Uusi ei ole tosiaan vielä julkinen, mutta pian... Tilanne on hetkellinen ja väliaikainen. Jos kuitenkin haluat nähdä tähän vaivaa, lähetä suoraan PR.

PS. Avaathan issuet jatkossa englanniksi, inklusiivisuuden ja johdonmukaisuuden vuoksi kielivalintamme on koodipuolella englannin kieli.

**Comment by bluelhf** [comment]
Ymmärrettävää — Uutta repoa odotellessa siis :)


### The conversation above is translated to English here:
---
## ― Link rot in HTML comments due to repository renaming
The HTML comments intended for people studying the source code of the webpage still point to the `digitoimistodude/dude` repository, which is no longer available (at least not publicly).

Offending links can be found in [GitHub search](https://github.com/digitoimistodude/dude-2020/search?q=github.com/digitoimistodude/dude).

A fix would involve simply changing all `github.com/digitoimistodude/dude` links to point to `github.com/digitoimistodude/dude-2020` instead.

---

― Hi! Good point, but it doesn't really matter, because this repo will soon be archived in favour of a new one. The new one is indeed not yet public, but will be soon... This is a very temporary situation. Nevertheless, if you want to spend some time on this, feel free to send a PR directly.

P.S. Please open issues in English in the future, our language of choice is English on the code side for the sake of inclusiveness and consistency.

---
― Understandable. I await the public release of the new repository :)

---
### End of translation.

**Comment by ronilaukkarinen** [comment]
Thank you for the issue and translation. Keep it up! 👍
